### ISSUE TITLE
Missing `OccurenceOrderPlugin` for `DIST`?

### ISSUE THREAD

**Issue by PAkerstrand** [rocjs/roc-package-webpack-web#11]
https://github.com/rocjs/roc-package-webpack-web/blob/master/extensions/roc-package-webpack-web-dev/src/webpack/index.js#L75-L77

I can't see that the `OccurenceOrderPlugin` is used in `DIST`-mode though, or am I missing something?

**Comment by dlmr** [comment]
We add the `OccurenceOrderPlugin` in `roc-package-webpack` as can be seen [here](https://github.com/rocjs/roc-package-webpack/blob/master/extensions/roc-package-webpack-dev/src/webpack/index.js#L146) for `DIST`.

What we can question is if we really need it only in `DEV` always for `web` and not for `node` but let's look at it again later.
