### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by vasklund** [rocjs/roc-package-webpack-web#13]
Just found this by accident, not sure if it's a typo or even relevant. Just close this if not :)

https://github.com/rocjs/roc-package-webpack-web/blob/master/extensions/roc-package-webpack-web-dev/src/webpack/index.js#L92

`managle` should be `mangle`, I guess?

**Comment by dlmr** [comment]
Looks like a bug, thanks for spotting it! 

Do you want to create a PR that fixes this issue? 🙂
